### ISSUE TITLE
Remove IPify GET request.

### ISSUE THREAD

**Issue by jpasantos** [EdwardChamberlain/namecheap_ddns#1]
This is not an issue but you can do this with user scripts.

Just add the following script:
curl "https://dynamicdns.park-your-domain.com/update?host=@&domain=DOMAIN&password=PASSWORD"

And run it every hour. You don't need to pass the IP since it will use the incoming connection's IP by default.

Also you're doing a get to https://api.ipify.org every 3 minutes to prevent you from sending a get to dynamicdns.park-your-domain.com/ if the IP wasn't changed. I don't see the benefit of this, just send it to Namecheap if it's changed or not

**Comment by EdwardChamberlain** [comment]
Thanks, I was not aware of the 'no ip' version of the URL. That's certainly useful. I will look at updating to use this method and removing the ipify get.

This project was made as an experiment on how to setup python > docker > unRAID CA so some stuff is perhaps a bit backwards! The main focus was to learn how to get logging setup and working, and how to get environment variables in nicely. Part of the way I did things was also because I wanted to be able to log when an IP was updated as well as updating the DDNS.

**Comment by jpasantos** [comment]
Also it can be interesting to have the sleep timer as a parameter. Every 3 seconds looks to short and I don't think most people need it that frequent

**Comment by EdwardChamberlain** [comment]
> Also it can be interesting to have the sleep timer as a parameter. Every 3 seconds looks to short and I don't think most people need it that frequent

This is available by setting the `APP_POLL_TIME` variable in the development branch.

**Comment by jpasantos** [comment]
Nice ;)
